### ISSUE TITLE
[Bug] FileNotFoundError: [Errno 2] No such file or directory: 'java'

### ISSUE THREAD

**Issue by Kobe-Zed** [tongye98/BinaryCodeSummary#1]
Hi, I encountered an issue while running the training script. Here are the details:
```
/usr/local/bin/python3 /root/.pycharm_helpers/pydev/pydevd.py --multiprocess --qt-support=auto --client localhost --port 42397 --file /data/BinaryCodeSummary-main/src/__main__.py train 
Connected to pydev debugger (build 232.10227.11)
2020-06-29 22:29:30,128 - INFO - root - Hello! This is xxxx's Transformer!
2020-06-29 22:29:32,362 - INFO - data - Use dataset already stored!
2020-06-29 22:29:34,446 - INFO - model - Build Model...
2020-06-29 22:29:34,645 - INFO - model - src_pos_emb = relative
2020-06-29 22:29:35,468 - INFO - model - src_pos_emb = relative
2020-06-29 22:29:36,101 - INFO - model - Total parameters number: 99462656
2020-06-29 22:29:36,189 - INFO - model - The model is built.
2020-06-29 22:29:36,193 - INFO - train - **********1 GPUs are used.**********
2020-06-29 22:29:36,193 - INFO - train - **********4 num_workers are used.**********
2020-06-29 22:29:36,587 - INFO - train - Adam(lr=0.0001, weight_decay=0, betas=[0.9, 0.999], eps=1e-08)
2020-06-29 22:29:36,587 - INFO - train - Scheduler = ReduceLROnPlateau
2020-06-29 22:29:36,588 - INFO - train - Train stats:
	device: cuda
	n_gpu: 1
	batch_size: 32
2020-06-29 22:29:36,588 - INFO - train - Epoch 1
2020-06-29 22:30:08,003 - INFO - train - Epoch   1, Step:     100, Sentence Loss:    85.969414, Lr: 0.000100, Tokens per sec:   1133
2020-06-29 22:30:36,367 - INFO - train - Epoch   1, Step:     200, Sentence Loss:    83.963554, Lr: 0.000100, Tokens per sec:   1241
2020-06-29 22:30:46,254 - INFO - train - Epoch   1: total training loss 574155.85
2020-06-29 22:30:46,280 - INFO - train - Beam Size = 4
Validating: 100%|███████████████████████████████| 30/30 [00:20<00:00,  1.43it/s]
2020-06-29 22:31:07,251 - INFO - train - use robertatokenizer to decode...
Traceback (most recent call last):
  File "/data/BinaryCodeSummary-main/src/train.py", line 312, in train_and_validate
    valid_duration_time = self.validate(valid_dataset, vocab_info)
  File "/data/BinaryCodeSummary-main/src/train.py", line 458, in validate
    bleu, rouge_l, meteor = eval_accuracies(model_generated, target_truth)
  File "/data/BinaryCodeSummary-main/src/validate.py", line 454, in eval_accuracies
    meteor_calculator = Meteor()
  File "/data/BinaryCodeSummary-main/src/validate.py", line 752, in __init__
    self.meteor_p = subprocess.Popen(meteor_cmd,
  File "/usr/local/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'java'
python-BaseException
^C
Process finished with exit code 130
```
It seems that the script requires java to run the METEOR evaluation, but java is not found in the environment. So I install the jdk envrionment on my linux platform, but it still does not work.
![image](https://github.com/tongye98/BinaryCodeSummary/assets/60780329/2ff800ca-46ce-43ee-9f79-08e1e7ec2846)

 Here is the relevant part of the source code in the project:
```
        self.meteor_p = subprocess.Popen(meteor_cmd,
                                         cwd=os.path.dirname(os.path.abspath(__file__)),
                                         env=env,
                                         stdin=subprocess.PIPE,
                                         stdout=subprocess.PIPE,
                                         stderr=subprocess.PIPE)
```
Could you please provide guidance on resolving this issue? Is there a specific version of Java required, or should I adjust the script to handle this dependency differently?

Thank you!

**Comment by iDTer** [comment]
EXM, have you solved the issue?
